set(PACLOADER_SOURCES
    src/glad/src/gl.c

    src/loader/initPacloader.c
    src/loader/mainShared.c
    src/loader/mainW.cpp
    src/loader/platform/platformBackend.cpp

    src/loader/config/config.c
    src/loader/config/configIni.c
    src/loader/config/iniParser.c
    src/loader/frontend/frontendApi.c

    src/loader/elfLoader/cppBridge.cpp
    src/loader/elfLoader/elfLoader.cpp
    src/loader/elfLoader/alsaCompatBridge.cpp
    src/loader/elfLoader/es1CompatBridge.cpp
    src/loader/elfLoader/filesystemBridge.cpp
    src/loader/elfLoader/gccBridge.cpp
    src/loader/elfLoader/guestTls.cpp
    src/loader/elfLoader/glxBridge.cpp
    src/loader/elfLoader/glHooks.cpp
    src/loader/elfLoader/graphicsBridge.cpp
    src/loader/elfLoader/ipcBridge.cpp
    src/loader/elfLoader/libcBridge.cpp
    src/loader/elfLoader/linuxStack.cpp
    src/loader/elfLoader/mathBridge.cpp
    src/loader/elfLoader/memoryManager.cpp
    src/loader/elfLoader/networkBridge.cpp
    src/loader/elfLoader/posixCompatBridge.cpp
    src/loader/elfLoader/pthreadBridge.cpp
    src/loader/elfLoader/randomDevice.cpp
    src/loader/elfLoader/regexBridge.cpp
    src/loader/elfLoader/sdl12Bridge.cpp
    src/loader/elfLoader/symbolResolver.cpp
    src/loader/elfLoader/termiosBridge.cpp
    src/loader/elfLoader/threadWatchdog.cpp
    src/loader/elfLoader/virtualDeviceRegistry.cpp
    src/loader/elfLoader/x11Bridge.cpp
    src/loader/elfLoader/pthread/pthreadBarrier.cpp
    src/loader/elfLoader/pthread/pthreadCond.cpp
    src/loader/elfLoader/pthread/pthreadEmu.cpp
    src/loader/elfLoader/pthread/pthreadMapper.cpp
    src/loader/elfLoader/pthread/pthreadMutex.cpp
    src/loader/elfLoader/pthread/pthreadOnce.cpp
    src/loader/elfLoader/pthread/pthreadRwlock.cpp
    src/loader/elfLoader/pthread/pthreadSemaphore.cpp
    src/loader/elfLoader/pthread/pthreadSpin.cpp
    src/loader/elfLoader/pthread/pthreadThread.cpp
    src/loader/elfLoader/pthread/pthreadTls.cpp

    src/loader/graphics/blitStretching.c
    src/loader/graphics/border.c
    src/loader/graphics/fpsLimiter.c
    src/loader/graphics/gluBridge.c
    src/loader/graphics/gpuVendor.c
    src/loader/graphics/pacloaderGraphics.c
    src/loader/graphics/sdlCalls.c

    src/loader/hardware/common/cardControl.c
    src/loader/hardware/common/jvs.c
    src/loader/hardware/ffb/sdlFfbBackend.c
    src/loader/hardware/namco/n2/n2.cpp
    src/loader/hardware/namco/n2/n2Audio.cpp
    src/loader/hardware/namco/n2/n2CardReader.cpp
    src/loader/hardware/namco/n2/n2Graphics.cpp
    src/loader/hardware/namco/n2/n2Hasp.cpp
    src/loader/hardware/namco/n2/n2Hook.cpp
    src/loader/hardware/namco/n2/n2Host.cpp
    src/loader/hardware/namco/n2/n2Input.cpp
    src/loader/hardware/namco/n2/n2Jvio.cpp
    src/loader/hardware/namco/n2/n2Kickback.cpp
    src/loader/hardware/namco/n2/n2SteeringIo.cpp
    src/loader/hardware/namco/n2/n2SystemCommand.cpp
    src/loader/hardware/namco/n2/n2Titles.cpp
    src/loader/hardware/namco/n2/n2VirtualDevices.cpp
    src/loader/hardware/namco/n2/csneo/n2CsNeo.cpp
    src/loader/hardware/namco/n2/csneo/n2CsNeoPcb.cpp
    src/loader/hardware/namco/n2/wmmt3/n2Wmmt3.cpp
    src/loader/hardware/namco/es1/es1.cpp
    src/loader/hardware/namco/es1/es1TestModeCompat.cpp
    src/loader/hardware/namco/es1/es1Jvs.cpp
    src/loader/hardware/namco/es1/es1Kickback.cpp
    src/loader/hardware/namco/es1/es1Network.cpp
    src/loader/hardware/namco/es1/es1VirtualDevices.cpp
    src/loader/hardware/namco/es1/es1AudioCompat.cpp
    src/loader/hardware/namco/es1/es1AlinCompat.cpp
    src/loader/hardware/namco/es1/es1CompatLayer.cpp
    src/loader/hardware/namco/es1/es1Titles.cpp
    src/loader/hardware/namco/es1/maximumHeat3d/es1MaximumHeat3D.cpp
    src/loader/hardware/namco/es1/wmmt4/es1Wmmt4.cpp
    src/loader/hardware/namco/es1/wmmt4/es1Wmmt4Card.cpp
    src/loader/hardware/namco/es1/wmmt4/es1Wmmt4Ffb.cpp
    src/loader/hardware/namco/es1/wmmt4/es1Wmmt4Network.cpp
    src/loader/hardware/namco/es1/wmmt4/es1Wmmt4Terminal.cpp

    src/loader/input/controlIniGen.c
    src/loader/input/sdlInput.c
    src/loader/log/log.c
    src/loader/redirections/filesystemPacloader.c
    src/loader/redirections/libcShared.c
    src/loader/redirections/memory.c)
